name: shzzz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Util package
  get: ^4.5.1
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^2.0.5
  logger: ^1.0.0
  equatable: ^2.0.2
  package_info: ^2.0.2
  permission_handler: any
  flutter_svg_provider: any
  share: ^2.0.4
  drift: ^1.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  url_launcher: ^6.0.18

  # UI package
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  ansicolor: ^2.0.1
  expandable: ^5.0.1
  flutter_switch: ^0.3.1
  flutter_markdown: ^0.6.2
  cached_network_image: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  photo_view: ^0.13.0
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  smooth_page_indicator: ^1.0.0+2
  modal_bottom_sheet: any
  another_flushbar: any
  flutter_screenutil: ^5.0.4
  flutter_native_splash: ^1.1.9
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^1.2.0
  fl_chart: ^0.41.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

  drift_dev: ^1.3.0
  build_runner: ^2.1.7

flutter_icons:
  android: true
  ios: true
  image_path: assets/ic_launcher.png

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

flutter_intl:
  enabled: true
